services:
  app:
    build: .
    container_name: app-php
    ports:
      - "8080:80"
    volumes:
      - ./Block4/MVC:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: test_database
      DB_USER: tatsiana
      DB_PASSWORD: userpass
    networks:
      - appnet

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: test_database
      MYSQL_USER: tatsiana
      MYSQL_PASSWORD: userpass
    volumes:  
      - db_data:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d  
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  db_data:    