name: Deploy to Alwaysdata

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout репозитория
              uses: actions/checkout@v3

            - name: Деплой на сервер
              uses: appleboy/scp-action@v0.1.7
              with:
                server: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                password: ${{ secrets.SSH_KEY }}
                protocol: sftp
                server-dir: /www/test/
                local-dir: Block2/Абстрактн_классы_интерфейсы/
                exclude: |
                  **/*.log
                timeout: 60000
                security: loose
                # dry-run: true
                dangerous-clean-slate: false
                

