name: Deploy to Alwaysdata

on:
    [push, pull_request]    

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Установка PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: "8.2"
                extensions: mbstring, pdo, pdo_sqlite
                coverage: none
            
            - name: Установка зависимостей
              run: composer install --no-progress --prefer-dist
              working-directory: Block3/eloquent-migrations

            - name: Создание .env для тестов
              run: |
                echo "APP_NAME=Laravel" > .env
                echo "APP_ENV=testing" >> .env
                echo "APP_KEY=" >> .env
                echo "APP_DEBUG=true" >> .env
                echo "APP_URL=http://localhost" >> .env
                echo "DB_CONNECTION=sqlite" >> .env
                echo "DB_DATABASE=:memory:" >> .env
              working-directory: Block3/eloquent-migrations

            - name: Генерация APP_KEY
              run: php artisan key:generate
              working-directory: Block3/eloquent-migrations

            - name: Прогон тестов Pest
              run: ./vendor/bin/pest
              working-directory: Block3/eloquent-migrations

    deploy:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout репозитория
              uses: actions/checkout@v3

            - name: Деплой на сервер
              uses: appleboy/scp-action@v0.1.7
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                password: ${{ secrets.SSH_KEY }}
                port: 22
                source: Block2/abstract_classes_interfaces/    
                target: "/home/${{ secrets.SSH_USER }}/www/test"                            
                timeout: 60s
                # dry-run: true
                

