name: Run Tests

on:
    push:
        branches:
            - block5-tests

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.2'
                extensions: mbstring, pdo, sqlite
                coverage: none

            - name: Установка зависимостей
              run: composer install --no-progress --prefer-dist
              working-directory: Block3/eloquent-migrations    

            - name: Create .env
              run: |
                cp .env.example .env || touch .env
                echo "APP_ENV=testing" >> .env
                echo "APP_KEY=" >> .env
                echo "DB_CONNECTION=sqlite" >> .env
                echo "DB_DATABASE=:memory:" >> .env
              working-directory: Block3/eloquent-migrations

            - name: Generate app key
              run: php artisan key:generate
              working-directory: Block3/eloquent-migrations

            - name: Run tests (Pest or PHPUnit)
              run: |
                if [ -f ./vendor/bin/pest ]; then
                  ./vendor/bin/pest
                else
                  ./vendor/bin/phpunit
                fi
              working-directory: Block3/eloquent-migrations
    
